[package]
name = "lab1_1"
version = "0.1.0"
authors = ["userr2232 <reynaldo.rz.26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed_width = "0.4.0"
serde = { version = "1.0", features = ["derive"] }